### ISSUE TITLE
jshint doesn't provide all depencies

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#10]
These dependencies doesn't appear to exist even sources are available in

<pre>
    npm(glob) < 0.1.0 is needed by jshint-2.9.1-5.1.noarch
    npm(readable-stream) = 1.1.0 is needed by jshint-2.9.1-5.1.noarch
</pre>

package avaialble: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/jshint

This happens with pre-pasted and without pre-pasting 'jshint.source' to 'jshint.spec'.

**Comment by marguerite** [comment]
there's a jshint package: https://build.opensuse.org/package/show/devel:languages:nodejs/jshint

**Comment by illuusio** [comment]
Ok then this is fixed and you have implemeted fixdep also that answered my question also.
