### ISSUE TITLE
bower.rb: github tags can be in more than one page WAS: latest build fails

### ISSUE THREAD

**Issue by coogor** [marguerite/nodejs-packaging#12]
Latest version of npkg (npkg-10.beta10-32.1.noarch) fails on fully patched Leap system:

test@linux-vmko:~/Application:ERP:Tryton:3.8/tryton-sao> npkg tryton-sao
Processing dependencies in package.json
1:tryton-sao
2:bower
Processing dependencies in bower.json
/usr/share/npkg/plugins/bower.rb:78:in `index': type mismatch: NilClass given (TypeError)
        from /usr/share/npkg/plugins/bower.rb:78:in`block (2 levels) in lookup'
        from /usr/share/npkg/plugins/bower.rb:77:in `each'
        from /usr/share/npkg/plugins/bower.rb:77:in`block in lookup'
        from /usr/share/npkg/plugins/bower.rb:38:in `each'
        from /usr/share/npkg/plugins/bower.rb:38:in`lookup'
        from /usr/share/npkg/plugins/bower.rb:97:in `install'
        from /usr/bin/npkg:92:in`block in <main>'
        from /usr/bin/npkg:85:in `glob'
        from /usr/bin/npkg:85:in`<main>'
test@linux-vmko:~/Application:ERP:Tryton:3.8/tryton-sao>

**Comment by coogor** [comment]
Hi, anything new on this?

**Comment by marguerite** [comment]
@coogor a big sorry...I AFK-ed for a while, now I'm back, will fix the issues ASAP.

**Comment by marguerite** [comment]
@coogor 

here's the reason, bower.json requires:
{"jquery"=>"~2.1.1", "bootstrap"=>"~3.3.4", "moment"=>"~2.10.2", "eonasdan-bootstrap-datetimepicker"=>"~4.7.14", "gettext.js"=>"~0.5.0", "d3"=>"~3.5.0", "c3"=>"~0.4.10"}

while jquery only has these versions:
["3.0.0", "3.0.0-rc1", "2.2.4", "1.12.4", "2.2.3", "1.12.3", "2.2.2", "1.12.2", "1.12.1+1", "2.2.1"]

none of these fits:
{"jquery"=>[">=2.1.1", "<2.2.0"]} ("jquery"=>"~2.1.1")

**Comment by marguerite** [comment]
well,

["3.0.0", "3.0.0-rc1", "2.2.4", "1.12.4", "2.2.3", "1.12.3", "2.2.2", "1.12.2", "1.12.1+1", "2.2.1"] 

is apprantly not correct.

https://github.com/jquery/jquery-dist/tags

my plugin can only read the 1st page. need to find a way to read all the pages

**Comment by marguerite** [comment]
fixed in v10.beta11
