### ISSUE TITLE
Can't package 'zxcvbn-cli' with new npm2rpm system

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#15]
openSUSE 42.2 generates this kind of problem. It done with npm2rpm script others are still mumbled with depencies:

[   33s] + node2rpm-server --prep
[   33s] /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/stage.rb:9:in `+': no implicit conversion of Symbol into String (TypeError)
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/stage.rb:9:in `block in method_missing'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/stage.rb:9:in `each'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/stage.rb:9:in `each_with_index'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/stage.rb:9:in `method_missing'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/parser.rb:22:in `parse'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:32:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:27:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:9:in `initialize'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `new'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `<top (required)>'
[   33s] 	from /usr/bin/node2rpm-server:23:in `load'
[   33s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   33s] error: Bad exit status from /var/tmp/rpm-tmp.NB2wus (%prep)

Spec can be found:
https://build.opensuse.org/package/show/home:illuusio:nodejs-packages/zxcvbn-cli

**Comment by marguerite** [comment]
@illuusio this is fixed in rubygem-rpmspec. but a leaf problem is still there. /etc/os-release (provided by openSUSE-release package) needed by rubygem-rpmspec is not required. I need to investigate into it.

**Comment by marguerite** [comment]
fixed. btw, node2rpm is at https://github.com/marguerite/rubygem-node2rpm.

**Comment by illuusio** [comment]
Ok now installing goes until then installing and then I got
```
[   33s] + node2rpm-server --prep
[   33s] /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:23:in `entries_suse': undefined method `map!' for nil:NilClass (NoMethodError)
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:13:in `entries'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/parser.rb:29:in `parse'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:32:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:27:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:9:in `initialize'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `new'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `<top (required)>'
[   33s] 	from /usr/bin/node2rpm-server:23:in `load'
[   33s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   33s] error: Bad exit status from /var/tmp/rpm-tmp.iwSYtn (%prep)
```
Nodejs version is 4 is it a problem shouldn’t be because this is Ruby exception.
