### ISSUE TITLE
Untaring semver.min.js.gz doesn't work

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#17]
I switched to upstream nodejs RPM packaging (from home:MargueriteSu:nodejs) again there is some troubles and this is one major one:
```
[   19s] Untaring /home/abuild/rpmbuild/SOURCES/semver-4.0.0/semver.min.js.gz
[   19s] tar: This does not look like a tar archive
[   19s] tar: Skipping to next header
[   19s] tar: Exiting with failure status due to previous errors
[   19s] /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:158:in `basename': no implicit conversion of nil into String (TypeError)
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:158:in `unpack'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:138:in `block in recursive_untar'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:133:in `glob'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:133:in `recursive_untar'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:145:in `block (2 levels) in recursive_untar'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:145:in `each'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:145:in `block in recursive_untar'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:133:in `glob'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:133:in `recursive_untar'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:24:in `prep'
[   19s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:11:in `<top (required)>'
[   19s] 	from /usr/bin/node2rpm-server:23:in `load'
[   19s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   19s] error: Bad exit status from /var/tmp/rpm-tmp.Xf49KX (%prep)
```
which can be found for example here: https://build.opensuse.org/package/live_build_log/home:illuusio:nodejs-bundle/stylelint/openSUSE_Leap_42.3/x86_64

**Comment by marguerite** [comment]
Ouch, looks like '.gz' should not be unpacked with tar?

**Comment by illuusio** [comment]
I looked it's just javascript that is Gzipped and I don't understand why.. should it be that there is file extension list or something. If it's 'tar.gz' then normal if it something else with .gz then just 'gzip -d'?

**Comment by marguerite** [comment]
I wrote a filter to find tarballs, it includes .gz referring to "tar.gz". maybe in this case, .gz is intended and shouldn't be unpacked to plain js. 

I will check it and consider to remove the .gz filter

**Comment by marguerite** [comment]
*.{gz,tgz,bz2,xz}

I used this to identify tarballs.

*.gz not only matches semver-4.0.0.tar.gz, but also matches semver.js.gz.

need a better filter

**Comment by illuusio** [comment]
I think *.tar.{gz,tgz,bz2,xz} will do and then if else *.{gz} for the rest..

**Comment by marguerite** [comment]
*.{tar.gz, tgz, bz2, xz}

I'm testing this. the regex you provided will match "semver-4.0.0.tar.tgz" which doesn't exist :-( while .tgz is the format distributed by npm registry :-(

**Comment by marguerite** [comment]
delivered again: https://github.com/marguerite/rubygem-node2rpm/commit/4484ad24565291920b3defbcf243a8898df777e6

close #17

**Comment by illuusio** [comment]
You are fast.. thanks..

**Comment by marguerite** [comment]
maybe a better fix (or feature) is like this:

if `semver.js.gz` is found, try find `semver.js` inside the same directory.

if found, delete the compressed one because it's redundant (should read semver-4.0.0.tgz codes to see if anything requires the compressed one directly).

if not, leave the compressed one there.

anyway it's just a leaf one to keep your openSUSE clean :-)

**Comment by illuusio** [comment]
In future you have all the time in the world to make this better but if this is hitting to OBS soon and makes packages build then I'm happy.

**Comment by marguerite** [comment]
it's already landed in home:MargueritieSu:nodejs...I won't comment if the fix is not landed in production environment :-).
