### ISSUE TITLE
Scripts doesn't support global dependencies linking

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#2]
If this this implemented it's not very easy to understand how to use. Original had 'nodejs-symlink-deps' script which was in RPM-macros as '%nodejs_symlink_deps'. 

I don't know is there way symlink automatic or even semi-automic without user intervention and that makes most of packages non-working state.

**Comment by marguerite** [comment]
can you explain what is "global dpendencies linking"? any document to refer to?

I didn't implement this at all

**Comment by illuusio** [comment]
node packages seems to have this sub-dir that have it's dependencies which nodejs-symlink-deps tried to solve and they were linked global nodejs repo as they don't duplicate disk usage

**Comment by illuusio** [comment]
I think I mean something like this in ruby

<pre>
#!/usr/bin/ruby
require 'rubygems'
require 'json'
str = ""
packagename = ARGV[0]
nodedir = "/usr/lib/node_modules/"
packagedir = nodedir + packagename
localmoduledir = packagedir + "node_modules/"
File.open(packagedir + "/package.json",'r:UTF-8') {|f| str = f.read}
js = JSON.parse(str)
Dir.mkdir("node_modules")
deppackagename = ""
js["dependencies"].each do |f|
    deppackagename = f.shift
    if Dir[nodedir + deppackagename] != nil
        if File.exists?("node_modules/" + deppackagename) == false
            File.symlink(nodedir + deppackagename, "node_modules/" + deppackagename)
        end
    end
end
</pre>

I can do it but I'm as I said very lousy in Ruby

**Comment by marguerite** [comment]
Do you mean:

/usr/lib/node_modules/a => /usr/lib/node_modules/b/node_modules/a?

Or in the other direction?

Save disk space for this package or other packages?

**Comment by marguerite** [comment]
But I think both ways can be handled by my packaging tool in 'tool' directory. I just didn't finish the toolkit yet. do no need to manually do that in the future.

**Comment by marguerite** [comment]
My aim for nodejs packaging in openSUSE is like this:

I just upload a `phantomjs.json` (finished), all the downloaded tarballs(finished), and a specfile modified from my template.

and nodejs-packaging will do the rest, including, eg:
- untar all the tarball (easy to do)
- create a hierarchy of directories in buildroot (working)
- copy the content of the tarball to the right place under the hierachy (todo)
- build, if there's any `.node` in the hierachy (todo)
- package, with dependencies automatically handled (finished)

in the "content copy" step, of course I'll use symlink in the hierachy to minimize the bundle.

in the future, I'll use other ruby scripts to read the generate `.json` files existing on OBS, to find the most common modules/versions. then create a `nodejs-modules-common` package to serve all. (then the "content copy" step will be:  a, symlink if the required dependency is inside `-common` package; b, symlink if the bundle has already had this module with the same version; c, copy the content).

That is, you don't need to create separate packages for every nodejs module any more. Just create the package that you really wanted, like `phantomjs`, `gulp` while leave other works for my tool. 

Currently, the bytes you wrote to create the package sometimes are even more than the bytes the nodejs module itself contains. that's not good

**Comment by illuusio** [comment]
So bundle all the tools with npm like bundles. Suits me but I think I'll go with Redhat-style building for a while.. Symlinks doesn't eat that much disk space..

**Comment by marguerite** [comment]
does 500kb vs 5kb make a difference to you？gulp bundle is 500kb，gulp standalone is 5kb. I dont want to package 95 packages to save 495kb，because in that case I have to write more than 495kb of specfile. and 495kb doesn't make any difference for most of the users.

**Comment by illuusio** [comment]
I have enough disk space for having both and it's not about the size of packages it's about the way of packaging things. Python, Perl and other happily package every project package in own spec file. Bundles are ok with nodejs-applications like Atom, jslint and etc problems arise when you need specific nodejs-project.  I just don't understand what are the benefits against using normal npm why write so much ruby stuff when you have working and tested package manager already? I don't mean to be cruel just wondering how to migrate to new system without losing my nodejs.
But openSUSE does what openSUSE wants and I do what I do to get my work done.. it's the spirit of open source at the best we don't have to get along just use the same projects.

**Comment by marguerite** [comment]
@illuusio 

Well, you need to read the README.md of this project :-) I have documented why we switch this way.

You're right about npm vs my ruby scripts. npm is good. but it can't be used in RPM packaging. when you need specific nodejs project, it's better using npm install.

But look again, how many of us will occasionally need, eg, `nodejs-path-is-absolute` package?

None. If you're developing your own nodejs project, you must be using npm. while if you're a normal end user, what the hell is that package about :-)

Most of the times, users just need the `application`. eg `atom`, `phantomjs`...so why maintain 400+ packages for a single application? it will drive you crazy when updating.

That is, openSUSE will host nodejs applications only in the future (of course I still give the ability to package separate packages in my toolkit)

How to migrate to the new system? just delete all the dependency packages and just package the application you want. You can see `phantomjs-prebuilt` in home:MargueriteSu:branches:devel:languages:nodejs. it's packaged with the help of the `nova` tool inside tool directory. you can see /usr/share/nova/README.md in v10-beta.

And of course you can do what you want to do to get your work done. I just think my way is better and easier for the maintenance.

**Comment by illuusio** [comment]
Yes valid points but some do-hell-lotta-with-those-packages and I maintain over 800 package of nodejs rpms so (opensuse mainepo only have non-mainantained 300) so don't come to me to tell how difficult and frustrating it is. I delete my repo-packages and keep my work underground as always. Just for the note: if you like to get some feedback don't get overreacting if someone disagrees or have different opinion.
Now I be silent and don't file any bugs or anything and just get-doing-my-dang this bug is closed anyway so no need to talk any more.

**Comment by marguerite** [comment]
?? why did you take my suggestion as order or something? I don't think 800 packages is maintainable by myself. but if you can, just continue maintaining it (And I still don't understand why you dislike to maintain just a few applications while in favor of 800 packages?). I closed the bug because I'll implement the missing feature (maybe in a different way). Anyway I'll keep the old behavior possible, that's why `scripts/random-pick.rb` exists.

**Comment by illuusio** [comment]
I don't like to maintain 800 packages. I just get to that ;). I bymyself I more likely to maintain JSHint and other that I need and nothing else. I just need those tools in mywork and they should be available also for build server so I get into that trouble. I'll convert them to schema now that I understand what you are up to.
