### ISSUE TITLE
 Dependency tokens must begin with alpha-numeric

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#20]
Sometimes requires and provides end like this:

```
[   22s] Finding  Provides: /usr/lib/rpm/nodejs.prov
[   22s] Finding  Requires(interp): 
[   22s] Finding  Requires(rpmlib): 
[   22s] Finding  Requires(verify): 
[   22s] Finding  Requires(pre): 
[   22s] Finding  Requires(post): 
[   22s] Finding  Requires(preun): 
[   22s] Finding  Requires(postun): 
[   22s] Finding  Requires(pretrans): 
[   22s] Finding  Requires(posttrans): 
[   22s] Finding  Requires: /usr/lib/rpm/nodejs.req
[   23s] error: Dependency tokens must begin with alpha-numeric, '_' or '/': >=. 0.0
[   23s] npm(graceful-readlink) = 1.0.0
[   23s] nodejs(engine) >= 0.8.0
[   23s] 
[   23s] error: Failed to find Requires:
[   23s] Provides: zxcvbn-cli = 1.0.6-8.1 npm(zxcvbn-cli) = 1.0.6 own(ansi-styles) = 2.2.1 own(escape-string-regexp) = 1.0.5 own(ansi-regex) = 2.0.0 own(has-ansi) = 2.0.0 own(strip-ansi) = 3.0.1 own(supports-color) = 2.0.0 own(chalk) = 1.1.3 own(colors) = 1.0.3 own(cli-table) = 0.3.1 own(graceful-readlink) = 1.0.1 own(commander) = 2.9.0 own(zxcvbn) = 4.2.0
[   23s] Requires(rpmlib): rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
[   23s] Requires: npm(graceful-readlink)
[   23s] 
[   23s] 
[   23s] RPM build errors:
[   23s]     Dependency tokens must begin with alpha-numeric, '_' or '/': >=. 0.0
[   23s] npm(graceful-readlink) = 1.0.0
[   23s] nodejs(engine) >= 0.8.0
[   23s] 
[   23s]     Failed to find Requires:
[   23s] 
[   23s] lamb24 failed "build zxcvbn-cli.spec" at Tue Sep  5 09:13:47 UTC 2017.
```
Package can be found on: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/zxcvbn-cli

**Comment by marguerite** [comment]
looks like it generates a "npm(graceful-readlink) >= .0.0" string, which couldn't be recognized by rpm. still debugging

**Comment by marguerite** [comment]
I also noticed these issues:

https://github.com/marguerite/rubygem-node2rpm/issues/2

https://github.com/marguerite/rubygem-node_semver/issues/1

**Comment by marguerite** [comment]
it's related to https://github.com/marguerite/rubygem-node_semver

node_semver renders ">= 1.0.0" into [">=.0.0", "=1.0.0"]

will take a look at it tomorrow.

node_semver is under refactoring, I just finished factoring the single version part and the version comparison part. I didn't have time to refactor the range part. maybe it's time to do that.

**Comment by illuusio** [comment]
I'll try to open this on correct packages so bugs are in right place.. take your time.

**Comment by marguerite** [comment]
@illuusio it's okay for you to open issues here. because I am the only one who can find out which gem does things bad by manually inserting debug stuff into ruby codes :-( eg, see:

https://build.opensuse.org/package/rdiff/home:MargueriteSu:branches:devel:languages:nodejs/zxcvbn-cli?opackage=zxcvbn-cli&oproject=home%3Ailluusio%3Anodejs-bundle&rev=5

**Comment by marguerite** [comment]
delivered: https://github.com/marguerite/rubygem-node_semver/commit/e20d7c1b3a327f4beb9faebc82cdfcac74951e01

close #20
