### ISSUE TITLE
New dependency tracking problem rises

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#22]
As most automatic dependency tracking problems has vanished there is more to come:
```
[   47s] Finding  Requires: /usr/lib/rpm/nodejs.req
[   47s] error: Dependency tokens must begin with alpha-numeric, '_' or '/': >=>= 1.5.0
[   47s] npm(nomnom) < 1.6.0
[   47s] npm(JSV) >=>= 4.0.0
[   47s] npm(JSV) < 4.1.0
[   47s] nodejs(engine) >= 0.8.0
[   47s] 
[   47s] error: Failed to find Requires:
[   47s] Provides: jsonlint = 1.6.2-9.1 npm(jsonlint) = 1.6.2 own(ansi-styles) = 1.1.0 own(has-color) = 0.1.7 own(strip-ansi) = 0.1.1 own(chalk) = 0.4.0 own(underscore) = 1.6.0 own(nomnom) = 1.8.1
[   47s] Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
[   47s] Requires: npm(ansi-styles) >= 1.0.0 npm(ansi-styles) < 1.1.0 npm(nomnom)
[   47s] 
[   47s] 
[   47s] RPM build errors:
[   47s]     Dependency tokens must begin with alpha-numeric, '_' or '/': >=>= 1.5.0
[   47s] npm(nomnom) < 1.6.0
[   47s] npm(JSV) >=>= 4.0.0
[   47s] npm(JSV) < 4.1.0
[   47s] nodejs(engine) >= 0.8.0
[   47s] 
[   47s]     Failed to find Requires:
[   47s] 
[   47s] wildcard3 failed "build jsonlint.spec" at Wed Sep  6 13:20:31 UTC 2017.
```
from https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/jsonlint
and

```
[   27s] error: Dependency tokens must begin with alpha-numeric, '_' or '/': >=. 0.0
[   27s] npm(mime-db) = 1.24.0
[   27s] npm(mime-db) <. 0.0
[   27s] npm(mime-db) >= 2.0.0
[   27s] npm(mime-db) < 3.0.0
[   27s] npm(statuses) >=. 0.0
[   27s] npm(statuses) = 1.3.1
[   27s] npm(statuses) <. 0.0
[   27s] npm(statuses) >= 2.0.0
[   27s] npm(statuses) < 3.0.0
[   27s] nodejs(engine) >= 0.8.0
```
from https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/hexo-server

**Comment by illuusio** [comment]
Never ending swamp.. it seems..

**Comment by marguerite** [comment]
well...that's nodejs...I'll check it again :-(

**Comment by marguerite** [comment]
@illuusio can you please tell me what '>= 1.5.x' will expand? I'm a little confused...

because literally 1.5.x itself means '>=1.5.0 <1.6.0', but what is '>= 1.5.x'?

**Comment by marguerite** [comment]
@illuusio can you please tell me what '>= 1.5.x' will expand? I'm a little confused...

because literally 1.5.x itself means '>=1.5.0 <1.6.0', but what is '>= 1.5.x'?

**Comment by illuusio** [comment]
Kind of hard question but I say everything above 1.5 but under 1.6 is correct (just forget last .x because it ain't something we need to take care of).
It took a while to seek but I think it would need to be done this way: https://serverfault.com/questions/411444/rpm-set-required-somepackage-0-5-0-and-somepackage-0-6-0/411491.

So for rpm version 1.5.x would be 'somepackage >= 1.5, somepackage < 1.6'.

**Comment by marguerite** [comment]
@illuusio actually it was the correct behavior...eg ">=(whitespace here)1.0.0", should not be interpreted as '>= & 1.0.0' => ‘>=.0.0 & 1.0.0', but should be interpreted as '>=1.0.0'. so '>= 1.5.x' is '>=1.5.x' and then 1.5.x is [>=1.5.0, <1.6.0], then [>=>= 1.5.0, <1.6.0] comes...maybe if:

* 1.0.x version or 1.x.x version
* just two elements eg '>=' and '1.5.x'
* then '>=' should be filled to '>=0.0.0'

then it'll be '>=0.0.0 >=1.5.0 < 1.6.0', and finally generates [>=1.5.0, <1.6.0]

**Comment by illuusio** [comment]
@marguerite Yes it seems correct but again '>=1.5,<1,6' is also correct but honestly '>=1.5.0,<1.6.0' is bullet proof. Nodejs 'flexible' version scheme is also painful to adapt.

**Comment by illuusio** [comment]
Ok then there can be depency that is available as own() but not npm() like in 'https://build.opensuse.org/package/binary/home:illuusio:nodejs-bundle/js-beautify?arch=x86_64&filename=js-beautify-1.6.3-9.2.noarch.rpm&repository=openSUSE_Leap_42.3' where I needed to build config-chain to satisfy depencies but it's also with rpm package but marked as 'own(config-chain)' and package requires 'npm(config-chain)'

**Comment by marguerite** [comment]
oh I see, this is a wrong behavior.

**Comment by illuusio** [comment]
I think this have been solve in PR so I close this
