### ISSUE TITLE
nodejs(engine) should be removed from depencies

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#23]
As there is nodejs4 - nodejs8 it would be easier to remove that from dependencies that are auto generated.

**Comment by marguerite** [comment]
you mean it will force you to manually select a nodejs in specfile?

the node() will parse every node requires in every package.json, and calculate the min and max.

so if you use nodejs in this range, it's safe.

as I remembered, some ancient nodejs modules requires 0.10...if it's forced. it can't be used with modern ones who live in 4.0.
