### ISSUE TITLE
Question: why doesn't my spec work?

### ISSUE THREAD

**Issue by z3ntu** [marguerite/nodejs-packaging#24]
See https://build.opensuse.org/package/show/hardware:razer/nodejs-less. The spec works on openSUSE_Leap_42.3 (which apparently doesn't have this project included) and doesn't work on openSUSE_Tumbleweed (which apparently includes this project). Any idea how I can fix this error because I need the `lessc` compiler for another package.

**Comment by illuusio** [comment]
You can try my packaged version from https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/lessc

**Comment by z3ntu** [comment]
@illuusio I have tried branching your package but without changes the package doesn't build either. See https://build.opensuse.org/package/show/hardware:razer/lessc

**Comment by illuusio** [comment]
You still need newer nodejs-packaging and rubygem-node2rpm, rubygem-node_semver to make it build also aggregate some packages from marguerite-repos.
Not very easy task but just but mine repo to meta-data <path> and also devel:languages:ruby. It should do the trick.
If you not familiar with that please see: https://build.opensuse.org/project/meta/home:illuusio:nodejs-bundle for example.

**Comment by z3ntu** [comment]
Isn't there an easier way to just get lessc on Tumbleweed? :/ I just need that package as a build requirement for another one so I don't care at all about how badly it is done as long as it works.

**Comment by illuusio** [comment]
Aggregate rpm from my repo or just use it from there or use npm to get it. Currently rebuilding repos but soon it should be updated.

**Comment by marguerite** [comment]
If you just want less in Factory, you can manually copy the files needed in specfile to make a package and submit.

But if you want an elegant way to package nodejs, try my tool. It may be the only way to properly handle node dependencies.

The one in Factory was the old one (the one didn’t split to node_semver/rpmspec/node2rpm), it wasn’t working sometimes and is unmaintained.

I didn’t update that package because someone in SUSE don’t like the bundle way and want to invent another way to separately package node modules. So in short, mine is the working way but people don’t like my theory, so I am still waiting for my competitors:-)

**Comment by marguerite** [comment]
see nodejs-emojione in Factory to find the manual way without nodejs-packaging.

**Comment by illuusio** [comment]
I don't care when it's easy 💃 after that.. I don't know.. Would they like to have some mega packager with all node packages separated? Npm does same as this tool.

**Comment by marguerite** [comment]
They think a bot can do the maintenance (update/review) jobs, and they want another bot to do the separate packaging. I think they dont want the mega packager with thousands of packages either.

We are intelligent human beings, and we met so many troubles even packaging bundlely. Personally I think it is a mission impossible.

So when I think I am ready, I will update nodejs-packaging in Factory anyway

**Comment by z3ntu** [comment]
I've used this now: https://build.opensuse.org/package/rdiff/hardware:razer/polychromatic?linkrev=base&rev=17 . Thanks :) It's really the opposite of beautiful but it's working.

**Comment by illuusio** [comment]
I see.. not very beatifull version. I think you would be more happy with aggregating because every time I update less it would be blowing up to you..

**Comment by marguerite** [comment]
as you had found a way out, I close this now
