### ISSUE TITLE
Depencies get slashed out big time

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#25]
Depencies parsing is missing there lines >=0.0.1 < 1.0.0 because of Regexp in nodejs-req.js. It leads to situation where package have all depencies but requires them outside also like:
https://build.opensuse.org/package/binary/home:illuusio:nodejs-bundle/jsonlint?arch=x86_64&filename=jsonlint-1.6.2-12.1.x86_64.rpm&repository=openSUSE_Leap_42.3.
One can't install this package and packager needs to add dependency by hand.

**Comment by marguerite** [comment]
working on it

**Comment by marguerite** [comment]
Fixed

**Comment by illuusio** [comment]
Yes depencies get parsed but in Requires they are npm(Something) and in Provides they are own(Something) so they can't get together.

**Comment by marguerite** [comment]
provides and requires are parsed separately. 

it’s because something unkown and I am working on it

**Comment by marguerite** [comment]
I found the cause:

rpm feed nodejs-packaging with all its packaged files at one time before, now it feeds us one by one.

I need to rewrite nodejs.req

**Comment by marguerite** [comment]
Fixed. One leaf problem remains, the JSV will be changed to lowercase in buildroot, will debug it later

**Comment by marguerite** [comment]
Closed again
