### ISSUE TITLE
Packaging 'jshint' doesn't work

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#4]
@Ok. now 'jslint' is working and 'jshint' ain't working (tested with your package from home repo) and same goes with git version

<pre>
1:jshint
2:cli
3:glob
4:minimatch
5:lru-cache
6:sigmund
7:graceful-fs
8:inherits
9:exit
10:console-browserify
11:date-now
12:exit
13:htmlparser2
14:domhandler
15:domelementtype
16:domutils
17:domelementtype
18:domelementtype
19:readable-stream
/usr/share/nova/dependencies.rb:86:in `list': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/share/nova/dependencies.rb:91:in `block in list'
    from /usr/share/nova/dependencies.rb:87:in `each'
    from /usr/share/nova/dependencies.rb:87:in `list'
    from /usr/share/nova/dependencies.rb:91:in `block in list'
    from /usr/share/nova/dependencies.rb:87:in `each'
    from /usr/share/nova/dependencies.rb:87:in `list'
    from /usr/share/nova/dependencies.rb:122:in `write'
    from /usr/bin/nova:12:in `<main>'
</pre>

**Comment by illuusio** [comment]
And 'jscs' throws:
<pre>
1:jscs
/usr/share/nova/history.rb:39:in `last': undefined method `-' for nil:NilClass (NoMethodError)
	from /usr/share/nova/dependencies.rb:49:in `block (2 levels) in list'
	from /usr/share/nova/dependencies.rb:44:in `each'
	from /usr/share/nova/dependencies.rb:44:in `block in list'
	from /usr/share/nova/dependencies.rb:43:in `each'
	from /usr/share/nova/dependencies.rb:43:in `list'
	from /usr/share/nova/dependencies.rb:91:in `block in list'
	from /usr/share/nova/dependencies.rb:87:in `each'
	from /usr/share/nova/dependencies.rb:87:in `list'
	from /usr/share/nova/dependencies.rb:122:in `write'
	from /usr/bin/nova:12:in `<main>'
</pre>

**Comment by marguerite** [comment]
Ha...yes

Actually I implemented the standard semver for nodejs. 

But nodejs module developers made mistakes here and there, eg: this case:-(

jshint needs htmlparser2 3.8.3, while htmlparser2 needs readable-stream 1.1

Strictly, 1.1 just means 1.1.0, not 1.1.x

But readable-stream have no 1.1.0 version at all. The smallest 1.1.x version is 1.1.7.

But unfortunately we will not know the real purpose of the developer unless we try(sometimes they just want 1.1.0 exactly)

I need to add a checker that check if the resolved version exists. If not, use the most reasonable version.
