### ISSUE TITLE
npkg stops after bower download

### ISSUE THREAD

**Issue by coogor** [marguerite/nodejs-packaging#6]
run npkg on the package tryton-sao.
It creates a .json file with sao and bower included, but it does not download the files that bower would process
(run npm package inside tryton-sao/package directory to see remaining downloads)

**Comment by marguerite** [comment]
you mean the dependencies in bower.json are missing?

**Comment by marguerite** [comment]
currently npkg does not support dependencies in bower.json.

because it's totally another system.

here's how npkg works:

it querys "http://registry.npmjs.org/tryton-sao", and found the latest version of tryton-sao.

then process the dependencies based on http://registry.npmjs.org/tryton-sao.

finally download all the dependencies.

it just needs hours of tweaks to support devDependencies because devDependencies are also exposed via registry.npmjs.org.

but bower is another story:

we don't know the content of bower.json before the actual download.

can you provide me an online place that bower hosts dependencies for packages?

or we can implement bower support like this:

after all the work done for package.json, unpack the main package (tryton-sao) to see if there's 
any bower.json provided.

if so, process dependencies in bower.json, if not, quit.

**Comment by coogor** [comment]
Hi,

Am Montag, 15. Februar 2016, 06:35:52 schrieb Marguerite Su:

> currently npkg does not support dependencies in bower.json.
> 
> because it's totally another system.

...but it is frequently used...

> here's how npkg works:
> 
> it querys "http://registry.npmjs.org/tryton-sao", and found the latest
> version of tryton-sao.
> 
> then process the dependencies based on http://registry.npmjs.org/tryton-sao.
> 
> finally download all the dependencies.
> 
> it just needs hours of tweaks to support devDependencies because
> devDependencies are also exposed via registry.npmjs.org.
> 
> but bower is another story:
> 
> we don't know the content of bower.json before the actual download.

But somehow must the list of files that bower has to process be in the source 
tarball (of tryton-sao). npm develops/processes bower....

> can you provide me an online place that bower hosts dependencies for
> packages?
> 
> or we can implement bower support like this:
> 
> after all the work done for package.json, unpack the main package
> (tryton-sao) to see if there's any bower.json provided.
> 
> if so, process dependencies in bower.json, if not, quit.

That sounds like a good idea! that would process the other stuff where the 
package depends on.....

**Comment by marguerite** [comment]
try v10.beta7 in home:MargueriteSu:branches:devel:languages:nodejs 

it works for me, see the tryton-sao package in the same repository

**Comment by coogor** [comment]
Am Mittwoch, 17. Februar 2016, 08:28:40 schrieb Marguerite Su:

> try v10.beta7 in home:MargueriteSu:branches:devel:languages:nodejs
> 
> it works for me, see the tryton-sao package in the same repository

I get a runtime error. First I thought that was due to a wrong repo (the build 
for Leap was not available), but my Leap branch showed the same issue:

test@linux-vmko:~/tryton-sao> npkg tryton-sao
/usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': 
cannot load such file -- nokogiri (LoadError)
        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 
`require'
        from /usr/share/npkg/plugins/bower.rb:5:in `<module:Bower>'
        from /usr/share/npkg/plugins/bower.rb:1:in`<top (required)>'
        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 
`require'
        from /usr/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 
`require'
        from /usr/bin/npkg:8:in `<main>'
test@linux-vmko:~/tryton-sao> 

Thanks

## Axel

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

Freedom needs Software that respects freedom:

ThinkPad T520 running openSUSE Leap 42.1 (x86_64)
Kernel: 4.1.15-8-default
KDE: 5.16.0

**Comment by marguerite** [comment]
@coogor `nokogiri` is a rubygem...

```
sudo zypper in "rubygem(nokogiri)"
```

should resolve it

**Comment by coogor** [comment]
Am Freitag, 19. Februar 2016, 08:14:54 schrieb Marguerite Su:

> @coogor `nokogiri` is a rubygem...
> 
> ```
> sudo zypper in "rubygem(nokogiri)"
> ```
> 
> should resolve it

Indeed, is this a missing dependency in nodejs-packaging then?
For the rest, looks very good, thanks for making this possible!

Last question...to grunt the package afterwards - run as command in the post 
install section?

I will test the installation and let you know

BEst,
Axel

## 

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

Freedom needs Software that respects freedom:

ThinkPad T520 running openSUSE Leap 42.1 (x86_64)
Kernel: 4.1.15-8-default
KDE: 5.16.0

**Comment by marguerite** [comment]
@coogor 

> Indeed, is this a missing dependency in nodejs-packaging then?

in official release this will be fine.

> to grunt the package afterwards - run as command in the post install section?

Why did you still want to grunt the package? the `dist` directory has already been there.

**Comment by coogor** [comment]
Am Freitag, 19. Februar 2016, 20:01:12 schrieb Marguerite Su:

> > to grunt the package afterwards - run as command in the post install
> > section?
> > Why did you still want to grunt the package? the `dist` directory has
> > already been there.

No matter if it is not required.... 

Actually I'm struggeling with a ruby error again:

[   26s] /usr/lib64/ruby/2.1.0/fileutils.rb:525:in `rename': Invalid argument 
@ sys_fail2 - (/home/abuild/rpmbuild/BUILDROOT/tryton-
sao-3.8.3-0.x86_64/usr/lib/node_modules/tryton-
sao-3.8.3/node_modules/bower-1.7.7/lib/node_modules/github/api/v3.0.0, 
/home/abuild/rpmbuild/BUILDROOT/tryton-
sao-3.8.3-0.x86_64/usr/lib/node_modules/tryton-
sao-3.8.3/node_modules/bower-1.7.7/lib/node_modules/github/api/v3.0.0/v3.0.0) 
(Errno::EINVAL)
[   26s]        from /usr/lib64/ruby/2.1.0/fileutils.rb:525:in`block in mv'
[   26s]        from /usr/lib64/ruby/2.1.0/fileutils.rb:1573:in `block in 
fu_each_src_dest'
[   26s]        from /usr/lib64/ruby/2.1.0/fileutils.rb:1587:in 
`fu_each_src_dest0'
[   26s]        from /usr/lib64/ruby/2.1.0/fileutils.rb:1571:in 
`fu_each_src_dest'
[   26s]        from /usr/lib64/ruby/2.1.0/fileutils.rb:514:in`mv'
[   26s]        from /usr/lib/rpm/nodejs.rb:82:in `block in <main>'
[   26s]        from /usr/lib/rpm/nodejs.rb:78:in`each'
[   26s]        from /usr/lib/rpm/nodejs.rb:78:in `<main>'
[   26s] error: Bad exit status from /var/tmp/rpm-tmp.sjAPeo (%install)

Still nodejs-packaging 10.beta7

Cheers

## Axel

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

Freedom needs Software that respects freedom:

ThinkPad T520 running openSUSE Leap 42.1 (x86_64)
Kernel: 4.1.15-8-default
KDE: 5.16.0

**Comment by marguerite** [comment]
@coogor this has been fixed already...please give me the OBS URL of your project, I'll send my development build to you.

**Comment by coogor** [comment]
Am Samstag, 20. Februar 2016, 03:46:42 schrieb Marguerite Su:

> @coogor this has been fixed already...please give me the OBS URL of your
> project, I'll send my development build to you.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/marguerite/nodejs-packaging/issues/6#issuecomment-1865771
> 88

I have branched your packaging here:

https://build.opensuse.org/package/show/home:DocB:branches:home:MargueriteSu:branches:devel:languages:nodejs/nodejs-packaging

and tryton-sao is here:

https://build.opensuse.org/package/show/Application:ERP:Tryton:3.8/tryton-sao

Thanks

## Axel

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

This mail was _not scanned_ before sending.
It was sent from a secure Linux-Desktop:

ThinkPad T520
OS: openSUSE 13.2 (i586)
Kernel: 3.16.7-32-desktop
KDE: 4.14.9

**Comment by marguerite** [comment]
the `nodejs-packaging` in Application:ERP:Tryton:3.8 is v10.beta5, update to beta7 will fix the above issue...

**Comment by coogor** [comment]
Am Samstag, 20. Februar 2016, 07:38:43 schrieb Marguerite Su:

> the nodejs-packaging in Application:ERP:Tryton:3.8 is v10.beta5, update to
> beta7 will fix the above issue...

I see - as I made a local build, I thought it would override...obviously it 
does not.

Now i build with beta7, and get a new error - not sure, but looks like some 
parenthesis were not processes properly - although the message points to the 
changes file:
https://build.opensuse.org/package/live_build_log/Application:ERP:Tryton:3.8/tryton-sao/openSUSE_Leap_42.1/x86_64

Cheers
Axel

## 

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

Freedom needs Software that respects freedom:

ThinkPad T520 running openSUSE Leap 42.1 (x86_64)
Kernel: 4.1.15-8-default
KDE: 5.16.0

**Comment by marguerite** [comment]
well it's my development build, containing incomplete features.

the latest build failure is because I was implementing a filter to filter unneeded files like `a.bak`, `b~`, `c.md`...

**Comment by coogor** [comment]
Am Montag, 22. Februar 2016, 07:24:11 schrieb Marguerite Su:

> well it's my development build, containing incomplete features.
> 
> the latest build failure is because I was implementing a filter to filter
> unneeded files like `a.bak`, `b~`, `c.md`...

Yes, this happens in development. :-)
Will you let me know once I can try a new build?

Thanks

## Axel

Dr.-Ing. Axel K. Braun
Mobile: +49.173.7003.154
VoIP/Skype: axxite
PGP Fingerprint: CB03 964D 1CFA E87B AA63 53F3 1BD6 F53A EB48 EF22
Public Key available at http://www.axxite.com/axel.braun@gmx.de.asc

Freedom needs Software that respects freedom:

ThinkPad T520 running openSUSE Leap 42.1 (x86_64)
Kernel: 4.1.15-8-default
KDE: 5.16.0

**Comment by marguerite** [comment]
@coogor the latest source in my development branch on OBS should have this fixed

**Comment by coogor** [comment]
Am Mittwoch, 24. Februar 2016, 08:07:03 schrieb Marguerite Su:

> @coogor the latest source in my development branch on OBS should have this
> fixed

Tried the latest build, but error remains the same.

**Comment by marguerite** [comment]
@coogor sorry I didn't see your comments. reopened.

**Comment by coogor** [comment]
Thanks Marguerite.
Latest build gives the error:

[   67s] + cd /home/abuild/rpmbuild/BUILD
[   67s] + /usr/lib/rpm/nodejs.rb --mkdir
[   67s] Creating /home/abuild/rpmbuild/BUILDROOT/tryton-sao-3.8.3-8.1.x86_64/usr/lib/node_modules/tryton-sao-3.8.3
[   67s] Creating /home/abuild/rpmbuild/BUILDROOT/tryton-sao-3.8.3-8.1.x86_64/usr/lib/node_modules/tryton-sao-3.8.3/node_modules/bower-1.7.7
[   67s] + /usr/lib/rpm/nodejs.rb --copy
[   68s] /usr/lib64/ruby/2.1.0/fileutils.rb:1585:in `path': no implicit conversion of nil into String (TypeError)
[   68s]    from /usr/lib64/ruby/2.1.0/fileutils.rb:1585:in`fu_each_src_dest0'
[   68s]    from /usr/lib64/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
[   68s]    from /usr/lib64/ruby/2.1.0/fileutils.rb:440:in`cp_r'
[   68s]    from /usr/lib/rpm/nodejs.rb:171:in `block (3 levels) in <main>'
[   68s]    from /usr/lib/rpm/nodejs.rb:169:in`glob'
[   68s]    from /usr/lib/rpm/nodejs.rb:169:in `block (2 levels) in <main>'
[   68s]    from /usr/lib/rpm/nodejs.rb:163:in`glob'
[   68s]    from /usr/lib/rpm/nodejs.rb:163:in `block in <main>'
[   68s]    from /usr/lib/rpm/nodejs.rb:161:in`glob'
[   68s]    from /usr/lib/rpm/nodejs.rb:161:in `<main>'
[   68s] error: Bad exit status from /var/tmp/rpm-tmp.kOsdQf (%install)

**Comment by marguerite** [comment]
fixed.
