### ISSUE TITLE
Can't build defs bundle

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#7]
Csslint doesn't build and throws this error

<pre>
[   66s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --define 'disturl obs://build.opensuse.org/home:illuusio:nodejs-bundle/openSUSE_13.1/780d225b03794da54f14fbe031e86c61-defs' /home/abuild/rpmbuild/SOURCES/defs.spec
[   66s] Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.ZC86TN
[   66s] + umask 022
[   66s] + cd /home/abuild/rpmbuild/BUILD
[   66s] + /usr/lib/rpm/nodejs.rb --prep
[   66s] /usr/lib64/ruby/2.0.0/fileutils.rb:1551:in `stat': No such file or directory - /home/abuild/rpmbuild/SOURCES/package (Errno::ENOENT)
[   66s]    from /usr/lib64/ruby/2.0.0/fileutils.rb:1551:in `block in fu_each_src_dest'
[   66s]    from /usr/lib64/ruby/2.0.0/fileutils.rb:1567:in `fu_each_src_dest0'
[   66s]    from /usr/lib64/ruby/2.0.0/fileutils.rb:1549:in `fu_each_src_dest'
[   66s]    from /usr/lib64/ruby/2.0.0/fileutils.rb:508:in `mv'
[   66s]    from /usr/lib/rpm/nodejs.rb:125:in `block in <main>'
[   66s]    from /usr/lib/rpm/nodejs.rb:121:in `glob'
[   66s]    from /usr/lib/rpm/nodejs.rb:121:in `<main>'
[   66s] error: Bad exit status from /var/tmp/rpm-tmp.ZC86TN (%prep)
[   66s] 
</pre>

package can be found 'https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/defs'

**Comment by illuusio** [comment]
Same goes with 'https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/regenerator'

**Comment by marguerite** [comment]
you didn't copy Souces in .source to .spec for both packages

**Comment by illuusio** [comment]
hmmm.. ok i should do that by hand? Ok I didn't quite get it.. why does other work without I copy anything from .source to .spec?

**Comment by marguerite** [comment]
@illuusio the others you mentioned didn't work too. you can download the final rpm and unrpm it. it'll be empty.

**Comment by marguerite** [comment]
I can't do that automatically because when you prepare the json, the package doesn't exist at all (which was created by you by hand), so no specfile to place.

**Comment by illuusio** [comment]
JShint is the same and building works but ain't empty..
http://download.opensuse.org/repositories/home:/illuusio:/nodejs-bundle/openSUSE_13.2/noarch/jshint-2.9.1-4.1.noarch.rpm

which cannot be installed as it is missing depencies..

<pre>
# DO NOT CHANGE MANUALLY START
# pasted from %{name}.source generated by nova
# SOURCE PASTE HERE
# DO NOT CHANGE MANUALLY END
</pre>

So I put things from .source file between these tags.. i'll test..

**Comment by illuusio** [comment]
Ok now I have them building.. mostly my bad..
