### ISSUE TITLE
Can't build esparse bundle

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#8]
Esparse bundle building goes down like this

<pre>
[   51s] Processing files: esparse-0.1.2-4.1.noarch
[   51s] Finding  Provides: /usr/lib/rpm/nodejs.prov
[   51s] /usr/lib/rpm/nodejs.prov:32:in `+': no implicit conversion of nil into String (TypeError)
[   51s]    from /usr/lib/rpm/nodejs.prov:32:in `block in <main>'
[   51s]    from /usr/lib/rpm/nodejs.prov:27:in `each'
[   51s]    from /usr/lib/rpm/nodejs.prov:27:in `<main>'
[   51s] error: /usr/lib/rpm/nodejs.prov failed: 100
[   51s] error: Failed to find Provides:
[   51s] Provides: esparse = 0.1.2-4.1
[   51s] Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
[   51s] 
[   51s] 
[   51s] RPM build errors:
[   51s]     /usr/lib/rpm/nodejs.prov failed: 100
[   51s]     Failed to find Provides:
</pre>

 Package can be found: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/esparse

**Comment by marguerite** [comment]
The same as #7
